module.exports = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  TIME_SELECTED: 'TIME_SELECTED',
  APPT_DETAILS: 'APPT_DETAILS',
  SET_APPOINTMENT: 'SET_APPOINTMENT',
  SHOW_MODAL: 'SHOW_MODAL'

};
